apiVersion: storage.coreos.com/v1alpha1
kind: StorageCluster
metadata:
    name: swift
spec:
    type: swift
    storageNodes:
        - nodeName: node0
          storageNetwork:
            ips:
              - 10.96.0.150
          devices:
              - vdb1
              - vdc1
              - vdd1
        - nodeName: node1
          storageNetwork:
            ips:
              - 10.96.0.151
          devices:
              - vdb1
              - vdc1
              - vdd1
        - nodeName: node2
          storageNetwork:
            ips:
              - 10.96.0.151
          devices:
              - vdb1
              - vdc1
              - vdd1
