apiVersion: storage.coreos.com/v1alpha1
kind: StorageCluster
metadata:
    name: swift
spec:
    type: swift
    storageNodes:
        - nodeName: minikube
          storageNetwork:
            ips:
              - 10.0.0.150
          devices:
              - vdb1
              - vdc1
              - vdd1
